library(tidyverse)
f<- file.choose()
df<- read_csv(file = f, col_names = TRUE)
f <- file.choose()
df <- read_csv(file = f, col_names = TRUE)
df <- read_csv(file = f, col_names = TRUE)
head(df)
class(df)
str(df)
